os: windows
language: cpp

services:
  - docker
  
before_install:
  - docker pull yadoms/build_for_windows
  
script:
  - docker run --name docCon -e MAKE_PACKAGE=true -e YADOMS_BUILD_BRANCH=${YADOMS_BRANCH} yadoms/build_for_windows
#  - docker cp docCon:/yadoms/builds/package .
#  - ls -al package
  
#before_deploy:
  # Set up git user name and tag this commit
  #- git config --local user.name "YOUR GIT USER NAME"
  #- git config --local user.email "YOUR GIT USER EMAIL"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  #- git tag $TRAVIS_TAG  
  
# deploy:
#  provider: releases
#  api_key: "${GH_OAUTH}"
#  file_glob: true
#  file: package/*
#  skip_cleanup: true  
#  draft: true
#  overwrite: true
#  on:
#    all_branches: true
    